/**
 * Performing Rights Organizations (PROs)
 * Matches the database enum 'pro_society'
 */

export interface PRO {
  value: string;
  label: string;
}

export const PRO_LIST: PRO[] = [
  { value: "", label: "No PRO" },
  { value: "PRS", label: "PRS (UK)" },
  { value: "ASCAP", label: "ASCAP (USA)" },
  { value: "BMI", label: "BMI (USA)" },
  { value: "SOCAN", label: "SOCAN (Canada)" },
  { value: "AACIMH", label: "AACIMH" },
  { value: "ABRAC", label: "ABRAC" },
  { value: "ABRAMUS", label: "ABRAMUS" },
  { value: "ACAM", label: "ACAM" },
  { value: "ACCESS", label: "ACCESS" },
  { value: "ACDAM", label: "ACDAM" },
  { value: "ACEMLA", label: "ACEMLA" },
  { value: "ACUM", label: "ACUM" },
  { value: "ADAGP", label: "ADAGP" },
  { value: "ADAVIS", label: "ADAVIS" },
  { value: "ADDAF", label: "ADDAF" },
  { value: "AEPI", label: "AEPI" },
  { value: "AGADU", label: "AGADU" },
  { value: "AGAYC", label: "AGAYC" },
  { value: "AKKA/LAA", label: "AKKA/LAA" },
  { value: "AKM", label: "AKM (Austria)" },
  { value: "ALBAUTOR", label: "ALBAUTOR" },
  { value: "ALCS", label: "ALCS" },
  { value: "AMAR", label: "AMAR" },
  { value: "AMCOS", label: "AMCOS (Australia/NZ)" },
  { value: "AMPAL", label: "AMPAL" },
  { value: "AMRA", label: "AMRA" },
  { value: "AMUS", label: "AMUS" },
  { value: "ANACIM", label: "ANACIM" },
  { value: "APA", label: "APA" },
  { value: "APDAYC", label: "APDAYC" },
  { value: "APG-JAPAN", label: "APG-JAPAN" },
  { value: "APRA", label: "APRA (Australia/NZ)" },
  { value: "APSAV", label: "APSAV" },
  { value: "ARGENTORES", label: "ARGENTORES" },
  { value: "ARMAUTHOR", label: "ARMAUTHOR" },
  { value: "ARS", label: "ARS" },
  { value: "ARTISJUS", label: "ARTISJUS" },
  { value: "ASDAC", label: "ASDAC" },
  { value: "ASSIM", label: "ASSIM" },
  { value: "ATIDA", label: "ATIDA" },
  { value: "ATN", label: "ATN" },
  { value: "AUSTRO-MECHANA", label: "AUSTRO-MECHANA" },
  { value: "AUTODIA", label: "AUTODIA" },
  { value: "AUTORARTE", label: "AUTORARTE" },
  { value: "AUTVIS", label: "AUTVIS" },
  { value: "AWA", label: "AWA" },
  { value: "AWGACS", label: "AWGACS" },
  { value: "BACKOFFICE", label: "BACKOFFICE" },
  { value: "BBDA", label: "BBDA" },
  { value: "BCDA", label: "BCDA" },
  { value: "BEELDRECHT", label: "BEELDRECHT" },
  { value: "BGDA", label: "BGDA" },
  { value: "BILD-KUNST", label: "BILD-KUNST" },
  { value: "BMDA", label: "BMDA" },
  { value: "BNDA", label: "BNDA" },
  { value: "BONO", label: "BONO" },
  { value: "BSDA", label: "BSDA" },
  { value: "BUBEDRA", label: "BUBEDRA" },
  { value: "BUCUDA", label: "BUCUDA" },
  { value: "BUMA", label: "BUMA (Netherlands)" },
  { value: "BUMDA", label: "BUMDA" },
  { value: "BURAFO", label: "BURAFO" },
  { value: "BURIDA", label: "BURIDA" },
  { value: "BUS", label: "BUS" },
  { value: "BUTODRA", label: "BUTODRA" },
  { value: "CAL", label: "CAL" },
  { value: "CAPAC", label: "CAPAC" },
  { value: "CAPASSO", label: "CAPASSO" },
  { value: "CASH", label: "CASH (Hong Kong)" },
  { value: "CCL", label: "CCL" },
  { value: "CHA", label: "CHA" },
  { value: "CMRRA", label: "CMRRA" },
  { value: "COMPASS", label: "COMPASS" },
  { value: "COPY-DAN BILLEDKUNST", label: "COPY-DAN BILLEDKUNST" },
  { value: "COPYRO", label: "COPYRO" },
  { value: "COSCAP", label: "COSCAP" },
  { value: "COSGA", label: "COSGA" },
  { value: "COSOMA", label: "COSOMA" },
  { value: "COSOTA", label: "COSOTA" },
  { value: "COTT", label: "COTT" },
  { value: "CPSN", label: "CPSN" },
  { value: "CREAIMAGEN", label: "CREAIMAGEN" },
  { value: "CSCS", label: "CSCS" },
  { value: "DACS", label: "DACS" },
  { value: "DALRO", label: "DALRO" },
  { value: "DGA", label: "DGA" },
  { value: "DILIA ", label: "DILIA " },
  { value: "DIRECTORES", label: "DIRECTORES" },
  { value: "DIVA", label: "DIVA" },
  { value: "DP", label: "DP" },
  { value: "DPRS", label: "DPRS" },
  { value: "DRCC", label: "DRCC" },
  { value: "EAU", label: "EAU" },
  { value: "ECAD", label: "ECAD" },
  { value: "ECCO", label: "ECCO" },
  { value: "EDEM", label: "EDEM" },
  { value: "FILMAUTOR", label: "FILMAUTOR" },
  { value: "FILSCAP", label: "FILSCAP" },
  { value: "FLIM JUS", label: "FLIM JUS" },
  { value: "FONOPERU", label: "FONOPERU" },
  { value: "GEMA", label: "GEMA (Germany)" },
  { value: "GESAC", label: "GESAC" },
  { value: "GESTOR", label: "GESTOR" },
  { value: "GMR", label: "GMR" },
  { value: "HAA", label: "HAA" },
  { value: "HARRY FOX", label: "HARRY FOX (USA)" },
  { value: "HDS-ZAMP", label: "HDS-ZAMP" },
  { value: "HUNGART", label: "HUNGART" },
  { value: "ICE", label: "ICE" },
  { value: "ICG", label: "ICG" },
  { value: "IMJV", label: "IMJV" },
  { value: "IMRO", label: "IMRO (Ireland)" },
  { value: "IPRS", label: "IPRS" },
  { value: "JACAP", label: "JACAP" },
  { value: "JASRAC", label: "JASRAC (Japan)" },
  { value: "KAZAK", label: "KAZAK" },
  { value: "KCI", label: "KCI" },
  { value: "KODA", label: "KODA" },
  { value: "KOMCA", label: "KOMCA" },
  { value: "KOPIOSTO", label: "KOPIOSTO" },
  { value: "KOSA", label: "KOSA" },
  { value: "KOSCAP", label: "KOSCAP" },
  { value: "KUVASTO", label: "KUVASTO" },
  { value: "KYRGYZPATENT", label: "KYRGYZPATENT" },
  { value: "LAA", label: "LAA" },
  { value: "LATGA-A", label: "LATGA-A" },
  { value: "LATINAUTOR", label: "LATINAUTOR" },
  { value: "LATINNET", label: "LATINNET" },
  { value: "LIRA", label: "LIRA" },
  { value: "LITA", label: "LITA" },
  { value: "LITERAR-MECHANA", label: "LITERAR-MECHANA" },
  { value: "LVG", label: "LVG" },
  { value: "MACP", label: "MACP" },
  { value: "MASA", label: "MASA" },
  { value: "MCPS", label: "MCPS (UK)" },
  { value: "MCSC", label: "MCSC" },
  { value: "MCSK", label: "MCSK" },
  { value: "MCSN", label: "MCSN" },
  { value: "MCT", label: "MCT" },
  { value: "MESAM", label: "MESAM" },
  { value: "MINT", label: "MINT" },
  { value: "MISASIA", label: "MISASIA" },
  { value: "MLC", label: "MLC" },
  { value: "MRS", label: "MRS" },
  { value: "MSG", label: "MSG" },
  { value: "MUSICAUTOR", label: "MUSICAUTOR" },
  { value: "MUSICMARK", label: "MUSICMARK" },
  { value: "MUSIKEDITION", label: "MUSIKEDITION" },
  { value: "MUSIXMATCH", label: "MUSIXMATCH" },
  { value: "MUST", label: "MUST" },
  { value: "NASCAM", label: "NASCAM" },
  { value: "NCB", label: "NCB" },
  { value: "NMPA", label: "NMPA" },
  { value: "NORD-DOC", label: "NORD-DOC" },
  { value: "NS", label: "NS" },
  { value: "OMDA", label: "OMDA" },
  { value: "ONDA", label: "ONDA" },
  { value: "OSA", label: "OSA" },
  { value: "OTPDA", label: "OTPDA" },
  { value: "PAPPRI", label: "PAPPRI" },
  { value: "PROCAN", label: "PROCAN" },
  { value: "PROLITTERIS", label: "PROLITTERIS" },
  { value: "RAO", label: "RAO" },
  { value: "ROMS", label: "ROMS" },
  { value: "RUPIS", label: "RUPIS" },
  { value: "SABAM", label: "SABAM" },
  { value: "SABEM", label: "SABEM" },
  { value: "SACD", label: "SACD" },
  { value: "SACEM", label: "SACEM (France)" },
  { value: "SACEMLUXEMBOURG", label: "SACEMLUXEMBOURG" },
  { value: "SACENC", label: "SACENC" },
  { value: "SACERAU", label: "SACERAU" },
  { value: "SACK", label: "SACK" },
  { value: "SACM", label: "SACM" },
  { value: "SACVEN", label: "SACVEN" },
  { value: "SADA", label: "SADA" },
  { value: "SADAIC", label: "SADAIC" },
  { value: "SADEMBRA", label: "SADEMBRA" },
  { value: "SADH", label: "SADH" },
  { value: "SAIF", label: "SAIF" },
  { value: "SAMPRA", label: "SAMPRA" },
  { value: "SAMRO", label: "SAMRO (South Africa)" },
  { value: "SARRAL", label: "SARRAL" },
  { value: "SARTEC", label: "SARTEC" },
  { value: "SAS", label: "SAS" },
  { value: "SAYCE", label: "SAYCE" },
  { value: "SAYCO", label: "SAYCO" },
  { value: "SAZAS", label: "SAZAS" },
  { value: "SBACEM", label: "SBACEM" },
  { value: "SBAT", label: "SBAT" },
  { value: "SCAM", label: "SCAM" },
  { value: "SCD", label: "SCD" },
  { value: "SESAC", label: "SESAC (USA)" },
  { value: "SESAM", label: "SESAM" },
  { value: "SFF", label: "SFF" },
  { value: "SGA", label: "SGA" },
  { value: "SGACEDOM", label: "SGACEDOM" },
  { value: "SGAE", label: "SGAE" },
  { value: "SGDL", label: "SGDL" },
  { value: "SIAE", label: "SIAE (Italy)" },
  { value: "SICAM", label: "SICAM" },
  { value: "SLPRS", label: "SLPRS" },
  { value: "SNAC", label: "SNAC" },
  { value: "SOBODAYCOM", label: "SOBODAYCOM" },
  { value: "SOCIETE DE L'IMAGE", label: "SOCIETE DE L'IMAGE" },
  { value: "SOCINADA", label: "SOCINADA" },
  { value: "SOCINPRO", label: "SOCINPRO" },
  { value: "SODART", label: "SODART" },
  { value: "SODRAC", label: "SODRAC" },
  { value: "SOFAM", label: "SOFAM" },
  { value: "SOGEM", label: "SOGEM" },
  { value: "SOKOJ", label: "SOKOJ" },
  { value: "SOLAR", label: "SOLAR" },
  { value: "SOMAAP", label: "SOMAAP" },
  { value: "SOMAS", label: "SOMAS" },
  { value: "SOMEX", label: "SOMEX" },
  { value: "SONECA", label: "SONECA" },
  { value: "SONGCODE", label: "SONGCODE" },
  { value: "SONGWRITERS GUILD", label: "SONGWRITERS GUILD" },
  { value: "SOPE", label: "SOPE" },
  { value: "SOPROFON", label: "SOPROFON" },
  { value: "SORECOP", label: "SORECOP" },
  { value: "SORM", label: "SORM" },
  { value: "SORSA", label: "SORSA" },
  { value: "SOSA", label: "SOSA" },
  { value: "SOZA", label: "SOZA" },
  { value: "SPA", label: "SPA" },
  { value: "SPAC", label: "SPAC" },
  { value: "SPACEMF", label: "SPACEMF" },
  { value: "SPACQ", label: "SPACQ" },
  { value: "SPEDIDAM", label: "SPEDIDAM" },
  { value: "SPI", label: "SPI" },
  { value: "SPOTIFY", label: "SPOTIFY" },
  { value: "SPRE", label: "SPRE" },
  { value: "SQN", label: "SQN" },
  { value: "SSA", label: "SSA" },
  { value: "STEF", label: "STEF" },
  { value: "STEMRA", label: "STEMRA" },
  { value: "STIM", label: "STIM (Sweden)" },
  { value: "SUISA", label: "SUISA (Switzerland)" },
  { value: "SUISSIMAGE", label: "SUISSIMAGE" },
  { value: "SUOMEN KIRJAILIJALIITTO", label: "SUOMEN KIRJAILIJALIITTO" },
  { value: "TEATERAUTOR", label: "TEATERAUTOR" },
  { value: "TEOSTO", label: "TEOSTO (Finland)" },
  { value: "TEOSTOJAKO", label: "TEOSTOJAKO" },
  { value: "THE AUTHOR'S REGISTRY INC.", label: "THE AUTHOR'S REGISTRY INC." },
  { value: "THE SOCIETY OF AUTHORS", label: "THE SOCIETY OF AUTHORS" },
  { value: "TONO", label: "TONO" },
  { value: "TURKKBIR", label: "TURKKBIR" },
  { value: "UACRR", label: "UACRR" },
  { value: "UBC", label: "UBC" },
  { value: "UCMR-ADA", label: "UCMR-ADA" },
  { value: "UCOSO", label: "UCOSO" },
  { value: "UFFIC", label: "UFFIC" },
  { value: "UFFICIO LEGALE", label: "UFFICIO LEGALE" },
  { value: "UNAC", label: "UNAC" },
  { value: "UNISON", label: "UNISON" },
  { value: "UNMSAC", label: "UNMSAC" },
  { value: "UPC", label: "UPC" },
  { value: "UPN", label: "UPN" },
  { value: "UPRS", label: "UPRS" },
  { value: "VAGA", label: "VAGA" },
  { value: "VBK", label: "VBK" },
  { value: "VCP", label: "VCP" },
  { value: "VCS", label: "VCS" },
  { value: "VDFS", label: "VDFS" },
  { value: "VEGAP", label: "VEGAP" },
  { value: "VEVAM", label: "VEVAM" },
  { value: "VG WORT", label: "VG WORT" },
  { value: "VISART", label: "VISART" },
  { value: "VISCOPY", label: "VISCOPY" },
  { value: "WAMI", label: "WAMI" },
  { value: "WGA", label: "WGA" },
  { value: "WGAW", label: "WGAW" },
  { value: "WGJ", label: "WGJ" },
  { value: "WID CENTRE", label: "WID CENTRE" },
  { value: "WRITERS GUILD", label: "WRITERS GUILD" },
  { value: "YOUTUBE", label: "YOUTUBE" },
  { value: "ZAIKS", label: "ZAIKS" },
  { value: "ZAMCOPS", label: "ZAMCOPS" },
  { value: "ZAMP", label: "ZAMP" },
  { value: "ZAPA", label: "ZAPA" },
  { value: "ZAVOD IPS", label: "ZAVOD IPS" },
  { value: "ZIMRA", label: "ZIMRA" },
  { value: "ZPAP", label: "ZPAP" },
  { value: "ZPMP", label: "ZPMP" },
  { value: "ZPRS", label: "ZPRS" }
];

